import { format, isWithinInterval, parse, getDay } from 'date-fns';
import { Doctor } from './types';

// Simple translation dictionary
export const translations = {
  ka: {
    app_name: 'მედლინქი',
    app_tagline: 'უსაფრთხო სამედიცინო მესენჯერი',
    patient: 'პაციენტი',
    doctor: 'ექიმი',
    message: 'შეტყობინება',
    anamnesis: 'ანამნეზი',
    settings: 'პარამეტრები',
    inbox: 'შემომავალი',
    connections: 'კავშირები',
    search: 'ძიება',
    send: 'გაგზავნა',
    call: 'ზარი',
    block: 'დაბლოკვა',
    export: 'ექსპორტი',
    payment: 'გადახდა',
    vaccine: 'ვაქცინა',
    allergy: 'ალერგია',
    medication: 'მედიკამენტი',
    surgery: 'ოპერაცია',
    blood_type: 'სისხლის ჯგუფი',
    logout: 'გასვლა',
    delete: 'წაშლა',
    assistant: 'ასისტენტი',
    today: 'დღეს',
    yesterday: 'გუშინ',
    pending_requests: 'მოლოდინში',
    working_hours: 'სამუშაო საათები',
    after_hours: 'არასამუშაო საათები',
    urgent_msg: 'სასწრაფო შეტყობინება',
    urgent_call: 'სასწრაფო ზარი',
    silent_msg: 'ჩუმი გაგზავნა (უფასო)',
    outside_hours_banner: 'ექიმი ისვენებს. შეგიძლიათ გააგზავნოთ ჩუმი შეტყობინება ან გადაიხადოთ სასწრაფო პასუხისთვის.',
    pay_btn: 'გადახდა',
    role_switch: 'როლის შეცვლა',
    save: 'შენახვა',
    next: 'შემდეგი',
    back: 'უკან',
    skip: 'გამოტოვება',
    closed: 'დახურულია',
    // Auth
    welcome_back: 'მოგესალმებით',
    enter_phone: 'შეიყვანეთ ტელეფონის ნომერი',
    send_code: 'კოდის გამოგზავნა',
    verify: 'დადასტურება',
    enter_code: 'შეიყვანეთ კოდი',
    code_sent_to: 'კოდი გაიგზავნა ნომერზე',
    i_am_a: 'მე ვარ...',
    manage_patients: 'პაციენტების მართვა',
    find_doctors: 'ექიმების მოძიება',
    six_digit_code: '6-ნიშნა კოდი',
    terms_of_service: 'გაგრძელებით თქვენ ეთანხმებით მომსახურების პირობებს',
    // Inbox
    no_conversations: 'საუბრები არ მოიძებნა',
    find_colleagues: 'კოლეგების მოძიება',
    unread: 'წაუკითხავი',
    starred: 'რჩეული',
    all: 'ყველა',
    // Chat
    type_message: 'ტექსტის შეყვანა...',
    voice_message: 'ხმოვანი შეტყობინება',
    urgent_response: 'სასწრაფო პასუხი',
    timeline: 'ისტორია',
    manage_tags: 'თეგების მართვა',
    set_reminder: 'შეხსენება',
    document: 'დოკუმენტი',
    gallery: 'გალერეა',
    replying_to: 'პასუხი',
    chat_blocked: 'საუბარი დაბლოკილია',
    view_history: 'ისტორიის ნახვა',
    export_chat: 'ჩატის ექსპორტი',
    pay_urgent: 'გადახდა (5 GEL)',
    send_silent: 'ჩუმი გაგზავნა',
    doc_away_msg: 'ექიმი ისვენებს. გადაიხადეთ სასწრაფო შეტყობინებისთვის.',
    processing_payment: 'მიმდინარეობს გადახდა...',
    export_confirm: 'ჩატის ექსპორტი ღირს 25 GEL. გსურთ გაგრძელება?',
    export_confirm_title: 'ჩატის ექსპორტი',
    export_confirm_yes: 'დიახ, ექსპორტი',
    recording: 'ჩაწერა...',
    // Tags
    tag_urgent: 'სასწრაფო',
    tag_followup: 'შემდგომი',
    tag_chronic: 'ქრონიკული',
    tag_lab: 'ლაბორატორია',
    tag_new: 'ახალი პაციენტი',
    urgent_badge: 'სასწრაფო',
    silent_badge: 'ჩუმი',
    // Anamnesis
    demographics: 'დემოგრაფია',
    emergency: 'გადაუდებელი',
    allergies: 'ალერგიები',
    medications: 'მედიკამენტები',
    conditions: 'დიაგნოზები',
    surgeries: 'ოპერაციები',
    habits: 'ჩვევები',
    notes: 'შენიშვნები',
    dob: 'დაბადების თარიღი',
    sex: 'სქესი',
    sex_placeholder: 'მამრობითი / მდედრობითი',
    add_allergy: 'ალერგიის დამატება',
    add_medication: 'მედიკამენტის დამატება',
    add_condition: 'დიაგნოზის დამატება',
    add_surgery: 'ოპერაციის დამატება',
    name: 'სახელი',
    dose: 'დოზა',
    freq: 'სიხშირე',
    smoking: 'თამბაქო',
    alcohol: 'ალკოჰოლი',
    never: 'არასდროს',
    former: 'წარსულში',
    current: 'ამჟამად',
    socially: 'იშვიათად',
    frequently: 'ხშირად',
    emergency_contact: 'საკონტაქტო პირი',
    emergency_phone: 'საკონტაქტო ტელეფონი',
    fill_accurately: 'გთხოვთ შეავსოთ ზუსტი ინფორმაცია.',
    finish: 'დასრულება',
    next_step: 'შემდეგი',
    my_anamnesis: 'ჩემი ანამნეზი',
    last_updated: 'ბოლოს განახლდა',
    none_recorded: 'ჩანაწერი არ არის',
    no_items_added: 'ჩანაწერი ჯერ არ არის დამატებული',
    edit_history: 'ისტორიის რედაქტირება',
    // Doctor
    requests: 'მოთხოვნები',
    colleagues: 'კოლეგები',
    no_colleagues: 'კოლეგები ვერ მოიძებნა',
    weekly_schedule: 'კვირის განრიგი',
    vacations: 'შვებულება / გამონაკლისები',
    add_new: 'დამატება',
    current_balance: 'ბალანსი',
    withdraw: 'გატანა',
    history: 'ისტორია',
    full_name_ka: 'სრული სახელი (ქართ)',
    full_name_en: 'სრული სახელი (ლათ)',
    specialties: 'სპეციალობები',
    clinics: 'კლინიკები',
    address: 'მისამართი',
    after_hours_paging: 'არასამუშაო გამოძახება',
    assistants: 'ასისტენტები',
    manage_assistants: 'ასისტენტების მართვა',
    status_busy: 'სტატუსი: დაკავებული',
    status_active: 'სტატუსი: აქტიური',
    patients_see_away: 'პაციენტები გხედავენ როგორც "დაკავებული"',
    based_on_schedule: 'განრიგის მიხედვით',
    msg_price: 'შეტყობინების ფასი',
    call_price: 'ზარის ფასი',
    copy_id: 'ID-ს კოპირება',
    copied_id: 'ID დაკოპირებულია!',
    share_profile: 'პროფილის გაზიარება',
    accept: 'მიღება',
    decline: 'უარყოფა',
    search_doctors: 'ექიმების ძიება...',
    no_pending_requests: 'მოლოდინში მოთხოვნები არ არის',
    tab_profile: 'პროფილი',
    tab_schedule: 'განრიგი',
    tab_settings: 'პარამეტრები',
    start_date: 'დაწყების თარიღი',
    end_date: 'დასრულების თარიღი',
    reason_optional: 'მიზეზი (არასავალდებულო)',
    no_exceptions: 'გამონაკლისები არ არის დამატებული',
    after_hours_desc: 'პაციენტებს შეუძლიათ გამოგიგზავნონ ფასიანი სასწრაფო შეტყობინებები, როცა არ ხართ ხაზზე.',
    assistant_count: 'ასისტენტი მართავს თქვენს შემომავალს',
    // Settings
    preferences: 'პარამეტრები',
    language: 'ენა',
    notifications: 'შეტყობინებები',
    security: 'უსაფრთხოება',
    change_pin: 'PIN-ის შეცვლა',
    privacy_policy: 'კონფიდენციალობა',
    delete_account: 'ანგარიშის წაშლა',
    delete_confirm: 'ეს მოქმედება შეუქცევადია. ყველა თქვენი მონაცემი წაიშლება.',
    on: 'ჩართული',
    save_pin: 'PIN-ის შენახვა',
    enter_new_pin: 'შეიყვანეთ ახალი 4-ნიშნა PIN კოდი',
    cancel: 'გაუქმება',
    yes_delete: 'დიახ, წაშლა',
    // Connect
    scan_qr: 'დაასკანერეთ QR',
    enter_doctor_id: 'შეიყვანეთ ექიმის ID',
    ask_doctor_id: 'სთხოვეთ ექიმს მისი MedLink ID',
    doctor_not_found: 'ექიმი ვერ მოიძებნა',
    request_sent: 'მოთხოვნა გაგზავნილია',
    search_directory: 'დირექტორიაში ძიება...',
    request_connection: 'დაკავშირების მოთხოვნა',
    already_connected: 'უკვე დაკავშირებული',
    request_pending: 'მოთხოვნა გაგზავნილია',
    // Timeline
    add_event: 'მოვლენის დამატება',
    event_type: 'მოვლენის ტიპი',
    title: 'სათაური',
    description: 'აღწერა',
    date_time: 'თარიღი და დრო',
    symptom: 'სიმპტომი',
    note: 'ჩანაწერი',
    appointment: 'ვიზიტი',
    // Misc
    file: 'ფაილი',
    image: 'სურათი',
    scanning: 'სკანირება...',
    end_of_transcript: '-- ტრანსკრიპტის დასასრული --',
    pdf_saved: 'PDF შენახულია',
    medlink_transcript: 'MedLink ტრანსკრიპტი',
    secure_call: 'MedLink უსაფრთხო ზარი',
    wait_for_approval: 'დაელოდეთ ექიმის დადასტურებას.',
    check_id_try_again: 'შეამოწმეთ ID და სცადეთ ხელახლა',
    privacy_policy_text: 'MedLink პერსონალურ მონაცემთა დაცვის პოლიტიკა\n\n1. ჩვენ ვაგროვებთ მხოლოდ იმ ინფორმაციას, რომელიც აუცილებელია სამედიცინო კომუნიკაციისთვის.\n\n2. თქვენი სამედიცინო მონაცემები დაშიფრულია და მხოლოდ ავტორიზებულ მხარეებს აქვთ წვდომა.\n\n3. ჩვენ არ ვყიდით და არ ვაზიარებთ თქვენს მონაცემებს მესამე მხარეებთან.\n\n4. თქვენ გაქვთ უფლება მოითხოვოთ თქვენი მონაცემების წაშლა ნებისმიერ დროს.\n\n5. კომუნიკაცია ექიმსა და პაციენტს შორის კონფიდენციალურია.\n\n6. გადახდის ინფორმაცია დამუშავდება უსაფრთხო არხებით.',
    enter_doctor_id_placeholder: 'შეიყვანეთ ექიმის ID (მაგ. ML-1001)',
  },
  en: {
    app_name: 'MedLink',
    app_tagline: 'Secure Medical Messenger',
    patient: 'Patient',
    doctor: 'Doctor',
    message: 'Message',
    anamnesis: 'Anamnesis',
    settings: 'Settings',
    inbox: 'Inbox',
    connections: 'Connections',
    search: 'Search',
    send: 'Send',
    call: 'Call',
    block: 'Block',
    export: 'Export',
    payment: 'Payment',
    vaccine: 'Vaccine',
    allergy: 'Allergy',
    medication: 'Medication',
    surgery: 'Surgery',
    blood_type: 'Blood Type',
    logout: 'Logout',
    delete: 'Delete',
    assistant: 'Assistant',
    today: 'Today',
    yesterday: 'Yesterday',
    pending_requests: 'Pending Requests',
    working_hours: 'Working Hours',
    after_hours: 'After Hours',
    urgent_msg: 'Urgent Message',
    urgent_call: 'Urgent Call',
    silent_msg: 'Send Silently (Free)',
    outside_hours_banner: 'Outside working hours. You can send silently or pay for an urgent response.',
    pay_btn: 'Pay',
    role_switch: 'Switch Role',
    save: 'Save',
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    closed: 'Closed',
    welcome_back: 'Welcome Back',
    enter_phone: 'Enter your phone number',
    send_code: 'Send Code',
    verify: 'Verify',
    enter_code: 'Enter Code',
    code_sent_to: 'We sent a code to',
    i_am_a: 'I am a...',
    manage_patients: 'Manage patients & practice',
    find_doctors: 'Find doctors & get care',
    six_digit_code: '6-Digit Code',
    terms_of_service: 'By continuing you agree to our Terms of Service',
    no_conversations: 'No conversations found',
    find_colleagues: 'Find Colleagues',
    unread: 'Unread',
    starred: 'Starred',
    all: 'All',
    type_message: 'Type a message...',
    voice_message: 'Voice Message',
    urgent_response: 'Urgent Response',
    timeline: 'Timeline',
    manage_tags: 'Manage Tags',
    set_reminder: 'Set Reminder',
    document: 'Document',
    gallery: 'Gallery',
    replying_to: 'Replying to',
    chat_blocked: 'This conversation is blocked',
    view_history: 'VIEW HISTORY',
    export_chat: 'Export Chat',
    pay_urgent: 'Pay Urgent (5 GEL)',
    send_silent: 'Send Silent',
    doc_away_msg: 'Doctor is away. Pay to notify them immediately.',
    processing_payment: 'Processing Payment...',
    export_confirm: 'Export chat transcript costs 25 GEL. Proceed?',
    export_confirm_title: 'Export Chat',
    export_confirm_yes: 'Yes, Export',
    recording: 'Recording...',
    tag_urgent: 'Urgent',
    tag_followup: 'Follow-up',
    tag_chronic: 'Chronic',
    tag_lab: 'Lab Results',
    tag_new: 'New Patient',
    urgent_badge: 'Urgent',
    silent_badge: 'Silent',
    demographics: 'Demographics',
    emergency: 'Emergency',
    allergies: 'Allergies',
    medications: 'Medications',
    conditions: 'Conditions',
    surgeries: 'Surgeries',
    habits: 'Habits',
    notes: 'Notes',
    dob: 'Date of Birth',
    sex: 'Sex',
    sex_placeholder: 'Male / Female',
    add_allergy: 'Add allergy',
    add_medication: 'Add Medication',
    add_condition: 'Add condition',
    add_surgery: 'Add surgery',
    name: 'Name',
    dose: 'Dose',
    freq: 'Freq',
    smoking: 'Smoking',
    alcohol: 'Alcohol',
    never: 'Never',
    former: 'Former',
    current: 'Current',
    socially: 'Socially',
    frequently: 'Frequently',
    emergency_contact: 'Emergency Contact',
    emergency_phone: 'Contact Phone',
    fill_accurately: 'Please fill out your medical history accurately.',
    finish: 'Finish',
    next_step: 'Next Step',
    my_anamnesis: 'My Anamnesis',
    last_updated: 'Last updated',
    none_recorded: 'None recorded',
    no_items_added: 'No items added yet',
    edit_history: 'Edit History',
    requests: 'Requests',
    colleagues: 'Colleagues',
    no_colleagues: 'No colleagues found.',
    weekly_schedule: 'Weekly Schedule',
    vacations: 'Vacations & Exceptions',
    add_new: 'Add New',
    current_balance: 'Current Balance',
    withdraw: 'Withdraw',
    history: 'History',
    full_name_ka: 'Full Name (Georgian)',
    full_name_en: 'Full Name (English)',
    specialties: 'Specialties',
    clinics: 'Clinics',
    address: 'Address',
    after_hours_paging: 'After-Hours Paging',
    assistants: 'Assistants',
    manage_assistants: 'Manage Assistants',
    status_busy: 'Status: Busy',
    status_active: 'Status: Active',
    patients_see_away: 'Patients see you as away.',
    based_on_schedule: 'Based on your schedule.',
    msg_price: 'Msg Price',
    call_price: 'Call Price',
    copy_id: 'Copy ID',
    copied_id: 'ID copied!',
    share_profile: 'Share Profile',
    accept: 'Accept',
    decline: 'Decline',
    search_doctors: 'Search doctors...',
    no_pending_requests: 'No pending requests',
    tab_profile: 'Profile',
    tab_schedule: 'Schedule',
    tab_settings: 'Settings',
    start_date: 'Start Date',
    end_date: 'End Date',
    reason_optional: 'Reason (Optional)',
    no_exceptions: 'No exceptions added yet',
    after_hours_desc: 'Allow patients to send paid urgent messages when you are off.',
    assistant_count: 'assistant(s) managing your inbox',
    preferences: 'Preferences',
    language: 'Language',
    notifications: 'Notifications',
    security: 'Security',
    change_pin: 'Change Recovery PIN',
    privacy_policy: 'Privacy Policy',
    delete_account: 'Delete Account',
    delete_confirm: 'This action is permanent and cannot be undone. All your data will be wiped.',
    on: 'On',
    save_pin: 'Save PIN',
    enter_new_pin: 'Enter a new 4-digit PIN',
    cancel: 'Cancel',
    yes_delete: 'Yes, Delete Everything',
    scan_qr: 'Scan QR Code',
    enter_doctor_id: 'Enter Doctor ID',
    ask_doctor_id: 'Ask your doctor to show their MedLink ID',
    doctor_not_found: 'Doctor not found',
    request_sent: 'Request Sent!',
    search_directory: 'Search MedLink directory...',
    request_connection: 'Request Connection',
    already_connected: 'Already Connected',
    request_pending: 'Request Pending',
    add_event: 'Add Event',
    event_type: 'Event Type',
    title: 'Title',
    description: 'Description',
    date_time: 'Date & Time',
    symptom: 'Symptom',
    note: 'Note',
    appointment: 'Appointment',
    file: 'File',
    image: 'Image',
    scanning: 'Scanning...',
    end_of_transcript: '-- End of Transcript --',
    pdf_saved: 'PDF Saved',
    medlink_transcript: 'MedLink Transcript',
    secure_call: 'MedLink Secure Call',
    wait_for_approval: 'Wait for the doctor to approve your request.',
    check_id_try_again: 'Check the ID and try again',
    privacy_policy_text: 'MedLink Privacy Policy\n\n1. We collect only the information necessary for medical communication.\n\n2. Your medical data is encrypted and only accessible to authorized parties.\n\n3. We do not sell or share your data with third parties.\n\n4. You have the right to request deletion of your data at any time.\n\n5. Communication between doctor and patient is confidential.\n\n6. Payment information is processed through secure channels.',
    enter_doctor_id_placeholder: 'Enter Doctor ID (e.g. ML-1001)',
  },
};

export type TranslationKey = keyof typeof translations.ka;

export const formatCurrency = (amount: number) => `${amount} GEL`;

export const isAfterHours = (doctor: Doctor): boolean => {
  // Manual override: if doctor set themselves as busy, they are "after hours"
  if (doctor.isManuallyBusy) return true;

  const now = new Date();
  const dayIndex = getDay(now); // 0 = Sun, 1 = Mon
  const days = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'];
  const dayKey = days[dayIndex];

  const schedule = doctor.workingHours[dayKey];

  if (!schedule || !schedule.enabled) return true;

  const start = parse(schedule.start, 'HH:mm', now);
  const end = parse(schedule.end, 'HH:mm', now);

  return !isWithinInterval(now, { start, end });
};

export const generateId = () => Math.random().toString(36).substr(2, 9);
